GET http://localhost:4000/users/jlao

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "cryptoList": ["BTC", "ETH", "LTC"]
}

###
DELETE http://localhost:4000/users/jlao

###
PATCH http://localhost:4000/users/jlao
Content-Type: application/json

{
    "cryptoList": ["BTC", "ETH", "LTC", "DOGE", "USDT", "HEX", "BNB", "XLM"]
}